version: '3.9'

services:
  tests:
    build:
      context: .
    volumes:
      - ./:/usr/local/src

  maildev:
    image: appwrite/mailcatcher:1.0.0
    ports:
      - '10000:1080'

  request-catcher:
    image: appwrite/requestcatcher:1.0.0
    ports:
      - '10001:5000'