version: '3.9'

services:
  tests:
    build:
      context: .
    environment:
      - MAILGUN_API_KEY
      - MAILGUN_DOMAIN
      - SENDGRID_API_KEY
      - FCM_SERVER_KEY
      - TWILIO_ACCOUNT_SID
      - TWILIO_AUTH_TOKEN
      - TELNYX_API_KEY
      - TELNYX_PUBLIC_KEY
      - AUTHKEY_8KVVCLA3HL
    volumes:
      - ./src:/usr/local/src/src
      - ./tests:/usr/local/src/tests
      - ./phpunit.xml:/usr/local/src/phpunit.xml
      
  maildev:
    image: appwrite/mailcatcher:1.0.0
    ports:
      - '10000:1080'

  request-catcher:
    image: appwrite/requestcatcher:1.0.0
    ports:
      - '10001:5000'